require Pod::Executable.execute_command('node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]})',
  __dir__
]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
use_frameworks! :linkage => linkage.to_sym if linkage

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.eql?('hermes')
      def pod.build_type; Pod::BuildType.static_library end
    end
  end
end

target 'LoyalTeeBusiness' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
        build_config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        build_config.build_settings['ENABLE_BITCODE'] = 'NO'
        build_config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'YES'
        build_config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'

        # ✅ Force Hermes to generate dSYM and be installable
        if target.name == 'hermes'
          build_config.build_settings['SKIP_INSTALL'] = 'NO'
          build_config.build_settings['DEAD_CODE_STRIPPING'] = 'NO'
          build_config.build_settings['COPY_PHASE_STRIP'] = 'NO'
          build_config.build_settings['STRIP_INSTALLED_PRODUCT'] = 'NO'
          build_config.build_settings['INSTALL_PATH'] = '$(LOCAL_LIBRARY_DIR)/Frameworks'
        end
      end
    end
  end
end
